listen=YES
listen_ipv6=NO
anonymous_enable=YES
anon_root=/srv/ftp
local_enable=YES
write_enable=YES
anon_upload_enable=YES
anon_mkdir_write_enable=YES
anon_other_write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
ssl_enable=NO
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=31000
