# ProFTPd — CVE-2015-3306 mod_copy (CRITICAL)
# SITE CPFR/CPTO copies files without authentication
# Metasploit: exploit/unix/ftp/proftpd_modcopy_exec
ServerName "Metasploitable3 ProFTPd"
ServerType standalone
DefaultServer on
Port 2121
MaxInstances 10
User nobody
Group nogroup
DefaultRoot /srv/ftp
AllowOverwrite on
# mod_copy loaded — enables SITE CPFR / SITE CPTO without auth
LoadModule mod_copy.c
<Anonymous /srv/ftp>
  User ftp
  Group ftp
  AnonRequirePassword off
  <Limit LOGIN>
    AllowAll
  </Limit>
</Anonymous>
