[global]
   workgroup = WORKGROUP
   server string = Metasploitable3 Samba Server
   netbios name = METASPLOITABLE3
   security = user
   map to guest = Bad User
   username map script = /bin/sh -c 'echo %U'
   log file = /var/log/samba/log.%m
   max log size = 1000

[public]
   path = /srv/samba/public
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   comment = Insecure Public Share

[homes]
   comment = Home Directories
   browseable = no
   read only = no
   valid users = %S
